#!/bin/bash

# Julia link
julia=$1

# Benchmark properties
n=$2
solver=$3
linsys=$4

# Additional benchmarks for mkl
mkl_csr=$5
mkl_csc=$6

# Number of threads
min_nthreads=$7
max_nthreads=$8

# Filenames julia files
julia_mul1="iterative_my_csr.jl"
julia_mul2="iterative_mkl_csr.jl" 
julia_mul3="iterative_mkl_csc.jl"
julia_info="iterative_info.jl"
julia_plot="plotbenchmarks.jl"

# Create header for results
h=$(hostname)
d=$(date +%Y-%m-%d)
t=$(date +%H-%M-%S)
header="${h}__${d}__${t}"

# Create result folder 
mkdir "${solver}/${header}"

# Filenames for results
result1_csv="${solver}/${header}/result1.csv"
result2_csv="${solver}/${header}/result2.csv" 
result3_csv="${solver}/${header}/result3.csv"
results_txt="${solver}/${header}/results.txt"

# Write header to combined results
echo $header >> $results_txt
echo >> $results_txt

# Make a run and write properties to results
export JULIA_NUM_THREADS=$max_nthreads_julia
$julia $julia_info $n $linsys >> $results_txt
echo >> $results_txt

# Benchmark my_csr write results to csv and txt file
echo "MtSpMV.jl CSR"
echo "MtSpMV.jl CSR" >> $results_txt
echo "nthreads="
# Run benchmarks and write result to csv file
export JULIA_NUM_THREADS=1
export OMP_NUM_THREADS=1
for ((t=min_nthreads; t<=max_nthreads ; t++)); do
    echo $t
    export JULIA_NUM_THREADS=$t
    export OMP_NUM_THREADS=$t
    $julia $julia_mul1 $n $linsys >> $result1_csv
done
# Copy result from csv file to txt file with the combined results
cat $result1_csv >> $results_txt
echo >> $results_txt

# Benchmark mkl_csr write results to csv and txt file
if [ "$mkl_csr" == true ] ; then
    echo "MKLSparse.jl CSR"
    echo "MKLSparse.jl CSR" >> $results_txt
    echo "nthreads="
    # Run benchmarks and write result to csv file
    export JULIA_NUM_THREADS=1
    export OMP_NUM_THREADS=1
    for ((t=min_nthreads; t<=max_nthreads ; t++)); do
        echo $t
        export JULIA_NUM_THREADS=$t
        export OMP_NUM_THREADS=$t
        $julia $julia_mul2 $n $linsys >> $result2_csv
    done
    # Copy result from csv file to txt file with the combined results
    cat $result2_csv >> $results_txt
    echo >> $results_txt
fi

# Benchmark mkl_csc write results to csv and txt file
if [ "$mkl_csc" == true ] ; then
    echo "MKLSparse.jl CSC"
    echo "MKLSparse.jl CSC" >> $results_txt
    echo "nthreads="
    # Run benchmarks and write result to csv file
    export JULIA_NUM_THREADS=1
    export OMP_NUM_THREADS=1
    for ((t=min_nthreads; t<=max_nthreads ; t++)); do
	    echo $t
	    export JULIA_NUM_THREADS=$t
	    export OMP_NUM_THREADS=$t
	    $julia $julia_mul3 $n $linsys >> $result3_csv
    done
    # Copy result from csv file to txt file with the combined results
    cat $result3_csv >> $results_txt
    echo >> $results_txt
fi

# Plot results
echo "Plotting..."
$julia $julia_plot $solver $header $mkl_csr $mkl_csc

